#!/usr/bin/env bash
# Assemble the deployable site for Cloudflare Pages.
#
# Cloudflare Pages → project settings:
#   Build command:           bash deploy/build-site.sh
#   Build output directory:  _site
#   Framework preset:        None
#   (no environment variables or secrets required)
#
# This is a pure copy step — no Python is needed in Cloudflare's build image.
# The live explorer (src/city_explorer.html) is a static file that needs no
# build, and the offline dashboard (dist/permit_dashboard.html) is generated by
# build.py and committed, so it is already current. Re-run `python build.py`
# locally and commit dist/ whenever the underlying data export changes.
set -euo pipefail

out="${1:-_site}"
rm -rf "$out"
mkdir -p "$out"

cp src/city_explorer.html      "$out/index.html"              # the explorer = site root
cp dist/permit_dashboard.html  "$out/permit_dashboard.html"   # point-in-time offline dashboard
cp _headers                    "$out/_headers"                # security headers + CSP (Cloudflare reads this from the output root)

echo "Assembled '$out':"
ls -la "$out"
